version: "3.9"
services:
  app:
    container_name: go-demo
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    networks:
      - go-demo-network
  db:
    container_name: go-demo-db
    image: postgres:14.5
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ./persist/postgres:/var/lib/postgresql/data
      - ./DDL:/docker-entrypoint-initdb.d
    networks:
      - go-demo-network
  pgadmin:
    container_name: go-demo-pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    volumes:
      - ./persist/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    networks:
      - go-demo-network
  redis:
    container_name: go-demo-redis
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - ./persist/redis:/data
    networks:
      - go-demo-network
networks:
  go-demo-network:
    driver: bridge
